/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate sidebar from the docs-custom folder structure
  customSidebar: [{ type: "autogenerated", dirName: "." }],

  // Or you can create a sidebar manually if needed
  /*
  customSidebar: [
    "intro",
    {
      type: "category",
      label: "Appeal",
      items: ["guide-1/index", "guide-1/step-1"],
    },
  ],
   */
};

module.exports = sidebars;
